Module4 task1
htmlacademy-adaptive/2058165-sedona-27 pull request #4
Opened 2023-01-09 07:30 UTC by ya-broccoli

2023-01-09 08:08 UTC, Dima-Dim requested changes

2023-01-09 08:08 UTC, Dima-Dim commented on source/sass/blocks/form.scss
> +    flex-direction: row;
Не нужно переопределять то что уже определено тем же значением.

2023-01-09 08:08 UTC, Dima-Dim commented on source/sass/blocks/intro.scss
> +    br {
https://up.htmlacademy.ru/adaptive/27/criteries#d11

2023-01-09 08:08 UTC, Dima-Dim commented on source/sass/blocks/number-item.scss
> +    .break {
https://up.htmlacademy.ru/adaptive/27/criteries#d11 и это как будто уже другой блок.

2023-01-09 08:08 UTC, Dima-Dim commented on source/sass/blocks/presentation.scss
> +.video-image {
Другой блок из другого файла.

2023-01-09 08:59 UTC, ya-broccoli commented on source/sass/blocks/intro.scss
> +    br {
Дима, не поняла на счет этого критерия( там вроде про использование амперсанда, с чем можно и с чем нельзя.. а у меня тут тег br. Я такую штуку в скринкасте видела с тегом br, и решила, что так можно..

2023-01-09 09:02 UTC, ya-broccoli commented on source/sass/blocks/number-item.scss
> +    .break {
тут тоже вопрос по переносам: если у меня есть два тега br в одной фразе, как мне по очереди их скрывать? я добавила одному класс и теперь получается надо новый блок делать только из-за одного переноса? проще есть путь?

2023-01-09 09:05 UTC, ya-broccoli commented on source/sass/blocks/presentation.scss
> +.video-image {
тут, я с твоего позволения не буду пока переделывать, там будет видео и все поменяется.. или надо?)

2023-01-10 13:03 UTC, Dima-Dim commented on source/sass/blocks/checkbox.scss
> +    .checkbox__mark {
https://up.htmlacademy.ru/adaptive/27/criteries#d11

2023-01-10 13:03 UTC, Dima-Dim commented on source/sass/blocks/number-item.scss
>      br {
https://up.htmlacademy.ru/adaptive/27/criteries#d11

2023-01-10 13:03 UTC, merged